version: '3.8'

services:
  hand_tracking:
    image: ghcr.io/smartworkmcd/handtracking:latest
    container_name: hand-tracking
    restart: unless-stopped
    depends_on:
      - mqtt-broker
    environment:
      - BROKER_IP=mqtt-broker
      - BROKER_PORT=1883
      - BROKER_USER=admin
      - BROKER_PASSWORD=admin
      - CAMERA_ID=0
      - SHOW_SCREEN=False
    devices:
      - "/dev/video0:/dev/video0"
