version: "2"
services:
  projector:
    image: ghcr.io/smartworkmcd/projector:latest
    container_name: projector
    ports:
      - "8080:80" 

  objectdetection:
    image: ghcr.io/smartworkmcd/objectdetection:latest
    container_name: objectdetection
    devices:
      - /dev/video0:/dev/video0
    environment:
      - BROKER_IP=mqtt-broker
      - BROKER_PORT=1883
      - BROKER_USER=admin
      - BROKER_PASSWORD=admin

  kiosk:
    image: balenablocks/browser:latest
    container_name: kiosk
    environment:
      - BROWSER_URL=http://projector:8080
      - BROWSER_FULLSCREEN=true
      - BROWSER_DISABLE_NAVIGATION=true
      - KIOSK=true