version: '3.8'

services:
  projector:
    image: ghcr.io/smartworkmcd/projector:latest
    container_name: projector
    restart: unless-stopped
    depends_on:
      - mqtt-broker
    ports:
      - "8080:80"  # Expose projector on port 8080 (adjust if needed)
    labels:
      io.balena.features.supervisor-api: '1'  # Needed for device info or control
    networks:
      - custom_network

  objectdetection:
    image: ghcr.io/smartworkmcd/objectdetection:latest
    container_name: objectdetection
    restart: unless-stopped
    depends_on:
      - mqtt-broker
    devices:
      - /dev/video0:/dev/video0
    environment:
      - BROKER_IP=mqtt-broker
      - BROKER_PORT=1883
      - BROKER_USER=${BROKER_USER}
      - BROKER_PASSWORD=${BROKER_PASSWORD}
    networks:
      - custom_network

  kiosk:
    build: ./kiosk
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
      io.balena.features.kernel-modules: '1'
      io.balena.features.x11: '1'

  networks:
    custom_network:
      driver: bridge
