version: "2"
services:
  projector:
    image: ghcr.io/smartworkmcd/projector:lastest
    container_name: projector
    ports:
      - "8080:80" 
    environment:
      - BROKER_IP={{BROKER_IP}}
      - BROKER_PORT={{BROKER_PORT}}
      - BROKER_USER={{BROKER_USER}}
      - BROKER_PASSWORD={{BROKER_PASSWORD}}

  objectdetection:
    image: ghcr.io/smartworkmcd/objectdetection:latest
    container_name: objectdetection
    devices:
      - /dev/video0:/dev/video0
    environment:
      - BROKER_IP={{BROKER_IP}}
      - BROKER_PORT={{BROKER_PORT}}
      - BROKER_USER={{BROKER_USER}}
      - BROKER_PASSWORD={{BROKER_PASSWORD}}

  kiosk:
    image: balenablocks/browser:latest
    container_name: kiosk
    environment:
      - BROWSER_URL=http://projector:8080
      - BROWSER_FULLSCREEN=true
      - BROWSER_DISABLE_NAVIGATION=true
      - KIOSK=true