version: "2"
services:
  projector:
    image: ghcr.io/smartworkmcd/projector:lastest
    container_name: projector
    ports:
      - "8000:8000"
    environment:
      - BROKER_IP=${BROKER_IP}
      - BROKER_PORT=1883
      - BROKER_USER=admin
      - BROKER_PASSWORD=admin

  objectdetection:
    image: ghcr.io/smartworkmcd/objectdetection:latest
    container_name: objectdetection
    privileged: true
    devices:
      - "/dev/video0:/dev/video0"
    environment:
      - BROKER_IP=${BROKER_IP}
      - BROKER_PORT=1883
      - BROKER_USER=admin
      - BROKER_PASSWORD=admin
    # command: "while true; do sleep 1000; done"

  kiosk:
    image: balenablocks/browser:latest
    container_name: kiosk
    privileged: true
    environment:
      - LAUNCH_URL=http://projector:8000 # <--- CHANGE THIS LINE
      - BROWSER_FULLSCREEN=true
      - BROWSER_DISABLE_NAVIGATION=true
      - KIOSK=true
