version: '3.8'

services:
  hand_tracking:
    image: ghcr.io/smartworkmcd/handtracking:latest
    container_name: hand-tracking
    restart: unless-stopped
    environment:
      - BROKER_IP={{BROKER_IP}}
      - BROKER_PORT=1883
      - BROKER_USER=admin
      - BROKER_PASSWORD=admin
      - CAMERA_ID=0
      - SHOW_SCREEN=False
    devices:
      - "/dev/video0:/dev/video0"
  
  workstation_brain:    
    image: ghcr.io/smartworkmcd/workstationbrain:latest
    container_name: workstation-brain
    restart: unless-stopped
    depends_on:
      - mqtt-broker
      - hand_tracking
    environment:
      - BROKER_IP=mqtt-broker
      - BROKER_PORT=1883
      - BROKER_USER=admin
      - BROKER_PASSWORD=admin
